require: rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable

Metrics/MethodLength:
  Max: 40
  Exclude:
    - test/**/*.rb
Metrics/AbcSize:
  Exclude:
    - test/**/*.rb
Metrics/ClassLength:
  Exclude:
    - test/**/*.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
